# Generated by Django 3.1.dev20200307214613 on 2020-11-10 15:16

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_id', models.IntegerField()),
                ('renter_id', models.IntegerField()),
                ('room_id', models.IntegerField()),
                ('rental_date', models.DateField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roomAddress', models.TextField()),
                ('roomType', models.CharField(choices=[('Phòng trọ', 'Phòng trọ'), ('Chung cư mini', 'Chung cư mini'), ('Chung cư', 'Chung cư'), ('Nhà nguyên căn', 'Nhà nguyên căn')], max_length=100)),
                ('roomDescription', models.TextField(default='(Không có mô tả)')),
                ('price', models.FloatField()),
                ('owner_id', models.IntegerField()),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('Chưa cho thuê', 'Available'), ('Đã cho thuê', 'notAvailable')], max_length=20)),
                ('area', models.FloatField(default=0)),
                ('bathroom', models.IntegerField(default=0)),
                ('bedroom', models.IntegerField(default=1)),
                ('kitchen', models.IntegerField(default=0)),
                ('air_conditioning', models.IntegerField(default=0)),
                ('balcony', models.IntegerField(default=0)),
                ('waterPrice', models.IntegerField(default=0)),
                ('electricPrice', models.IntegerField(default=0)),
                ('postDate', models.DateField()),
                ('image1', models.ImageField(default=None, upload_to='pictures/')),
                ('image2', models.ImageField(default=None, upload_to='pictures/')),
                ('image3', models.ImageField(default=None, upload_to='pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=50, unique=True)),
                ('email', models.EmailField(default='a@gmail.com', max_length=254, verbose_name='Email address')),
                ('name', models.CharField(default='A', max_length=50)),
                ('birth', models.DateField(default='2020-11-9')),
                ('phone', models.CharField(default='0214567123', max_length=15)),
                ('address', models.CharField(default='', max_length=200)),
                ('user_type', models.CharField(default='admin', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
