# Generated by Django 3.1.dev20200307214613 on 2020-11-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0001_initial'),
    ]

    operations = [
                migrations.DeleteModel(
            name='RoomDescription',
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='air_conditioning',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='area',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='balcony',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='bathroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='electricPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='kitchen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='postDate',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='waterPrice',
            field=models.IntegerField(default=0),
        ),
    ]
