# Generated by Django 3.1.dev20200307214613 on 2020-11-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0003_auto_20201105_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
