# Generated by Django 3.1.dev20200307214613 on 2020-11-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0003_users_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50, unique=True)),
                ('email', models.EmailField(default='a@gmail.com', max_length=254, verbose_name='Email address')),
                ('name', models.CharField(default='A', max_length=50)),
                ('birth', models.DateField(default='2020-11-9')),
                ('phone', models.CharField(default='0214567123', max_length=15)),
                ('address', models.CharField(default='', max_length=200)),
                ('user_type', models.CharField(default='admin', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='confirmed',
        ),
    ]
