# Generated by Django 3.1.dev20200307214613 on 2020-11-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0004_auto_20201119_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
