# Generated by Django 3.1.dev20200307214613 on 2020-11-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0005_waitinglist_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.SmallIntegerField()),
                ('author', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
