# Generated by Django 3.1.dev20200307214613 on 2020-11-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0006_auto_20201108_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdetails',
            name='price',
            field=models.FloatField(),
        ),
    ]
