# Generated by Django 3.1.dev20200307214613 on 2020-12-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0007_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rater',
            field=models.CharField(default='', max_length=50),
        ),
    ]
