# Generated by Django 3.1.dev20200307214613 on 2020-12-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0008_rating_rater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(default='', max_length=10),
        ),
    ]
