# Generated by Django 3.1.dev20200307214613 on 2020-12-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0009_auto_20201204_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='room_id',
            field=models.SmallIntegerField(),
        ),
    ]
