# Generated by Django 3.1.dev20200307214613 on 2020-12-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0010_auto_20201204_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='id',
            field=models.SmallIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
