# Generated by Django 3.1.4 on 2020-12-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0013_auto_20201212_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('send_date', models.DateTimeField()),
            ],
        ),
    ]
