# Generated by Django 3.1.4 on 2020-12-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0015_roomdetails_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('room_id', models.IntegerField()),
            ],
        ),
    ]
