# Generated by Django 3.1.4 on 2020-12-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0016_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.SmallIntegerField()),
                ('author', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
