# Generated by Django 3.1.4 on 2020-12-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0017_waitingcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingcomment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
