# Generated by Django 3.1.4 on 2020-12-31 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_console', '0018_auto_20201231_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetails',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
